New event type added
Activiti/Activiti pull request #1167
Opened 2017-04-12 08:07 UTC by mike-jordan

2017-11-23 09:00 UTC, Salaboy commented
@mike-jordan thanks for this PR. Can you please rebase this pr to branch 6.x? 
@balsarori can you please check this one to see if it can be included in 6.x?

2017-11-23 09:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Activiti/Activiti?pullRequest=1167) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Activiti/Activiti?pullRequest=1167) before we can accept your contribution.<br/><hr/>**mike-jordan** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Activiti/Activiti?pullRequest=1167) it.</sub>

2017-12-04 18:50 UTC, Salaboy commented
@mike-jordan you need to sign our CLA (contributor agreement) first, without that we cannot merge the PR. Also notice that some quality checks are failing.

2017-12-07 08:23 UTC, Salaboy commented
@balsarori I can see that you are taking care of this PR, are we going to merge it?

2017-12-14 09:10 UTC, Salaboy commented
@balsarori should we close this one again? @mike-jordan is not answering any comments and this has been opened long time ago.

2017-12-28 10:47 UTC, mike-jordan commented
@balsarori  @Salaboy Sorry for late response. I have signed the CLA. The message cancelled event type would be helpful to have in the cases when an entity subscribed to the message gets cancelled.

2018-01-23 08:40 UTC, Salaboy commented
@balsarori can you review this and merge if needed? I would like to get your views on moving this to develop as well.

2018-01-23 08:41 UTC, Salaboy commented
@mike-jordan thanks for coming back to us. 
@balsarori can you please review this which is targeting 6.x? I would like to get your views on if we should move this to develop or not.

2018-01-31 17:04 UTC, Salaboy commented
@balsarori news about this?

2018-03-02 15:20 UTC, Salaboy commented
@balsarori can you please check this?

2018-03-06 10:25 UTC, balsarori requested changes

2018-03-06 10:25 UTC, balsarori commented on modules/activiti-engine/src/test/resources/org/activiti/engine/test/api/event/ActivityEventsTest.testActivityMessageBoundaryEventsOnSubProcess.bpmn20.xml
> +    <sequenceFlow id="cloudsequenceflow4" isImmediate="false" sourceRef="subProcess" targetRef="cloudformtask2">
This change is invalid (cloudendnoneevent2 will have no source sequence) and doesn't seem needed. Can you revert this change?

2018-03-06 10:25 UTC, balsarori commented on modules/activiti-engine/src/test/java/org/activiti/engine/test/api/event/ActivityEventsTest.java
> +    //assertEquals(ActivitiEventType.ACTIVITY_MESSAGE_RECEIVED, messageEvent.getType());
please remove this commented line.

2018-03-06 10:25 UTC, balsarori commented on modules/activiti-engine/src/test/java/org/activiti/engine/test/api/event/ActivityEventsTest.java
> +    assertDatabaseEventPresent(ActivitiEventType.ACTIVITY_MESSAGE_WAITING);
An assert ```assertDatabaseEventPresent(ActivitiEventType.ACTIVITY_MESSAGE_CANCELLED);``` is needed here (and other tests where message are checked if they exist in DB). The assert will file there is no ```ActivityMessageEventHandler``` for ```ACTIVITY_MESSAGE_CANCELLED``` events. Can you add a ```ActivityMessageEventHandler``` for the new event?

2018-03-06 10:27 UTC, balsarori commented
@mike-jordan thanks for the PR and sorry for the late review. Can you implement the requested changes?

2018-05-01 16:28 UTC, Salaboy commented
@mike-jordan any chance that can you look at the changes requested by @balsarori ?

2026-04-24 10:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Activiti/Activiti?pullRequest=1167) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Activiti/Activiti?pullRequest=1167) before we can accept your contribution.<br/><hr/>**mike-jordan** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Activiti/Activiti?pullRequest=1167) it.</sub>

2026-07-27 00:21 UTC, closed without merging