Fixed a possible null pointer exception in BaseElement, as well as go…
Activiti/Activiti pull request #1650
Opened 2017-12-29 10:34 UTC by fmcejudo

…ing for more java 8 enhancement and supporting BaseElement with tests.

2017-12-29 10:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Activiti/Activiti?pullRequest=1650) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Activiti/Activiti?pullRequest=1650) before we can accept your contribution.<br/><hr/>**francisco** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Activiti/Activiti?pullRequest=1650) it.</sub>

2021-04-13 08:23 UTC, erdemedeiros commented
Hi @fmcejudo, thank you for your submission. I'm really sorry o we took that long to handle it. If you're still around could you, please, sign License/CLA and update the PR.

2021-04-13 08:49 UTC, fmcejudo commented
Hi, still around! License signed. Thank for considering it.

2021-04-13 12:29 UTC, erdemedeiros commented
Don't forget to rebase your pull request that's currently in conflict with the `develop` branch.

2021-04-23 07:14 UTC, erdemedeiros requested changes
Hi @fmcejudo, please, do not touch to versions (files `VERSION` and `pom.xml`). You should be able to build your Pull Request without modifying those files. Let me know if you're encountering any problems related to that.
Header files should not be modified either: use the same existing header in the new files you add.

2021-04-23 08:21 UTC, fmcejudo commented
sorry, my fork was not in sync with yours and I messed it up a bit. it is already solved

2021-04-23 09:43 UTC, erdemedeiros reviewed
Thank you for the updates. You only missed the headers of `BaseElement` and `BaseElementTest`. Then it should be ready to merge.

2021-04-23 09:43 UTC, erdemedeiros commented on activiti-core/activiti-bpmn-model/src/main/java/org/activiti/bpmn/model/BaseElement.java
> + * Copyright 2019 Alfresco, Inc. and/or its affiliates.
Please, revert this change in the header and update the header of `BaseElementTest` to match this one.

2021-04-23 10:20 UTC, erdemedeiros approved these changes
LGTM!

2021-04-23 10:29 UTC, erdemedeiros commented
The CI is failing because it's detecting an extra white space at the end of the line `Copyright 2010-2020 Alfresco Software, Ltd. `. You need to fix it in `BaseElement` and `BaseElementTest`.

2021-04-23 16:02 UTC, merged