Activiti/Activiti#3460-Added application deployed event producer
Activiti/Activiti pull request #3471
Opened 2020-10-28 11:26 UTC by Giovanni007

Created the producer for the event application deployed. The goal is to generate the event that we can handle in Query to get information about the application and create an entity there. (we need it to return all the versions of an Application using an API)

2020-11-03 09:19 UTC, andrea-ligios requested changes
Everything seems fine apart from two very minor additions needed.

I'm not sure if this build problem is ephemeral, and hence a false positive: https://lgtm.com/projects/g/Activiti/Activiti/logs/rev/pr-bb6447d5c9c96f4b7024e584c6860c90772ea837/lang:java/stage:Build%20merge_53a3a4ce0250a1a344bfab08e2738a9740ce0fec

2020-11-03 09:19 UTC, andrea-ligios commented on activiti-core/activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/DeployedApplicationListener.java
> +}
Please add a newline character at line 38

2020-11-03 09:19 UTC, andrea-ligios commented on activiti-core/activiti-spring-boot-starter/src/main/java/org/activiti/spring/ApplicationDeployedEventProducer.java
> +    public void doStop() {
Please add a comment inside the empty method body to make Codacy happy

2020-11-03 11:51 UTC, andrea-ligios approved these changes

2020-11-04 08:57 UTC, erdemedeiros requested changes
Some minor details. LGTM otherwise.

2020-11-04 08:57 UTC, erdemedeiros commented on activiti-core/activiti-spring-boot-starter/src/main/java/org/activiti/spring/ApplicationDeployedEventProducer.java
> +    private static final String APPLICATION_DEPLOYED_EVENT_NAME= "SpringAutoDeployment";
I'm wondering if APPLICATION_DEPLOYMENT_NAME wouldn't be a better name for this constant. What do you think?

2020-11-04 08:57 UTC, erdemedeiros commented on activiti-core/activiti-spring-boot-starter/src/main/java/org/activiti/spring/ApplicationDeployedEventProducer.java
> +                        .createDeploymentQuery()
The deployment name can be filtered directly here and the `if` in the line `62` can be removed:
`.deploymentName()`.

2020-11-04 08:57 UTC, erdemedeiros commented on activiti-core/activiti-spring-boot-starter/src/main/java/org/activiti/spring/ApplicationDeployedEventProducer.java
> +    private List<ApplicationDeployedEvent> getApplicationDeployedEvents() {
I think you need either rename this method or remove the call to listeners from it: it's doing more than getting events; it's also calling listeners on them.

2020-11-04 10:54 UTC, Giovanni007 commented on activiti-core/activiti-spring-boot-starter/src/main/java/org/activiti/spring/ApplicationDeployedEventProducer.java
> +                        .createDeploymentQuery()
good catch, thanks!

2020-11-04 13:39 UTC, erdemedeiros approved these changes
LGTM

2020-11-04 13:39 UTC, merged