Activiti/Activiti#3498 Add diagram rendering for errored activities
Activiti/Activiti pull request #3618
Opened 2021-03-31 08:51 UTC by miguelruizdev

Addressing: Activiti/Activiti#3498

2021-03-31 17:01 UTC, zoltanpalfi approved these changes

2021-04-01 13:10 UTC, erdemedeiros requested changes
Nice improvement!
Here are some suggestions.

2021-04-01 13:10 UTC, erdemedeiros commented on activiti-core/activiti-image-generator/src/main/java/org/activiti/image/impl/DefaultProcessDiagramCanvas.java
> +    public void drawGatewayHighLightErrored(GraphicInfo graphicInfo) {
You can reuse some code here by extracting another method that takes the color as a parameter. In this way, both  `drawGatewayHighLightCompleted ` and `drawGatewayHighLightErrored` will call this new method but passing a different color.

2021-04-01 13:10 UTC, erdemedeiros commented on activiti-core/activiti-image-generator/src/main/java/org/activiti/image/impl/DefaultProcessDiagramCanvas.java
> +    public void drawEventHighLightErrored(int x,
Same here: you can extract a method that will be reused by both `drawEventHighLightCompleted` and `drawEventHighLightErrored`.

2021-04-01 13:10 UTC, erdemedeiros commented on activiti-core/activiti-image-generator/src/main/java/org/activiti/image/impl/DefaultProcessDiagramGenerator.java
> +            (int) graphicInfo.getHeight());
I'd prefer to have the entire `GraphicInfo` passed as a parameter, instead of splitting it into several parameters.

2021-04-01 13:10 UTC, erdemedeiros commented on activiti-core/activiti-image-generator/src/main/java/org/activiti/image/impl/DefaultProcessDiagramGenerator.java
> +        processDiagramCanvas.drawEventHighLightErrored((int) graphicInfo.getX(),
Same here: let's pass the entire `GraphicInfo`.

2021-04-02 08:14 UTC, erdemedeiros approved these changes
LGTM!

2021-04-02 08:28 UTC, merged