5.x supportin7.x
Activiti/Activiti pull request #3738
Opened 2021-10-12 05:26 UTC by AnkurChauhan-131

Add Activiti 5 compatibility code with Activiti5 Engine compatible code

2021-10-12 13:55 UTC, balsarori requested changes
@AnkurChauhan-131 can you remove the org.activiti.form package and all classes in it? That is not required.

2021-10-12 14:16 UTC, AnkurChauhan-131 commented
> @AnkurChauhan-131 can you remove the org.activiti.form package and all classes in it? That is not required.

Deleted engine/form package. But it seems Activit5 code that we have added in APS do refer to the files within engine/form package. So should i add them in APS itself

2021-10-12 14:21 UTC, balsarori commented
@AnkurChauhan-131 yes

2021-10-12 15:14 UTC, balsarori commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/FormService.java
> +/*
This file can be removed

2021-10-13 16:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Activiti/Activiti?pullRequest=3738) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Activiti/Activiti?pullRequest=3738) before we can accept your contribution.<br/><hr/>**Your Name** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Activiti/Activiti?pullRequest=3738) it.</sub>

2021-11-02 10:41 UTC, erdemedeiros commented
Covered by https://github.com/Activiti/Activiti/pull/3740

2021-11-02 10:41 UTC, closed without merging