Add extension points allowing execution of legacy Activiti 5 processes
Activiti/Activiti pull request #3740
Opened 2021-10-19 18:29 UTC by AnkurChauhan-131

Activiti5 in Activiti7

2021-10-19 18:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Activiti/Activiti?pullRequest=3740) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Activiti/Activiti?pullRequest=3740) before we can accept your contribution.<br/><hr/>**Your Name** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Activiti/Activiti?pullRequest=3740) it.</sub>

2021-10-28 11:23 UTC, erdemedeiros requested changes
Hi @AnkurChauhan-131,
You'll find below my feedback. For internal methods, it's better to avoid `public` scope, unless there is really a good reason for that.

2021-10-28 11:23 UTC, erdemedeiros commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/asyncexecutor/ExecuteAsyncRunnable.java
> +  public void runInternal(){
Can we have `protected` scope instead of `public`?

2021-10-28 11:23 UTC, erdemedeiros commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/helper/ErrorThrowingEventListener.java
> +  public void onEventInternal(ActivitiEvent event){
Same here, could it be `protected`?

2021-10-28 11:23 UTC, erdemedeiros commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/AbstractSetProcessDefinitionStateCmd.java
> +  public Void executeInternal(CommandContext commandContext,List<ProcessDefinitionEntity> processDefinitions){
`protected`?

2021-10-28 11:23 UTC, erdemedeiros commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/AbstractSetProcessDefinitionStateCmd.java
> +  public void createTimerForDelayedExecution(CommandContext commandContext, List<ProcessDefinitionEntity> processDefinitions) {
Is there any valid reason to change the scope here?

2021-10-28 11:23 UTC, erdemedeiros commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/AbstractSetProcessDefinitionStateCmd.java
> +  public void createTimerForDelayedExecutionInternal(CommandContext commandContext, ProcessDefinitionEntity processDefinition) {
`protected`?

2021-10-28 11:23 UTC, erdemedeiros commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/AbstractSetProcessDefinitionStateCmd.java
> +  public void changeProcessDefinitionState(CommandContext commandContext, List<ProcessDefinitionEntity> processDefinitions) {
`protected`?

2021-10-28 11:23 UTC, erdemedeiros commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/AbstractSetProcessInstanceStateCmd.java
> +  public Void executeInternal(CommandContext commandContext,ExecutionEntity executionEntity){
`protected`?

2021-10-28 11:23 UTC, erdemedeiros commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/AbstractSetProcessInstanceStateCmd.java
>        }
Would you mind taking the advantage that you're refactoring this code to remove the comment ` // All child executions are suspended` and extract a method `updateChildrenSuspensionState` from this block? This should improve the code readability.

2021-10-28 11:23 UTC, erdemedeiros commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/AbstractSetProcessInstanceStateCmd.java
>        }
Same here, consider removing the comment and extracting a method for it.

2021-10-28 11:23 UTC, erdemedeiros commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/AbstractSetProcessInstanceStateCmd.java
>        }
Extract method.

2021-10-28 11:23 UTC, erdemedeiros commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/AddCommentCmd.java
> +  public Comment executeInternal(CommandContext commandContext,String processDefinitionId){
`protected`?

2021-10-28 11:23 UTC, erdemedeiros commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/AddIdentityLinkForProcessDefinitionCmd.java
> +  public Void executeInternal(CommandContext commandContext,ProcessDefinitionEntity processDefinition) {
`protected`?

2021-10-28 11:23 UTC, erdemedeiros commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/AddIdentityLinkForProcessDefinitionCmd.java
> +  public Void executeInternal(CommandContext commandContext,ProcessDefinitionEntity processDefinition) {
`Void` --> `void`.

2021-10-28 11:23 UTC, erdemedeiros commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/AddIdentityLinkForProcessInstanceCmd.java
> +  public Void executeInternal(CommandContext commandContext,ExecutionEntity processInstance) {
`Void` --> `void`.

2021-10-28 11:23 UTC, erdemedeiros commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/AbstractSetProcessDefinitionStateCmd.java
> +  public Void executeInternal(CommandContext commandContext,List<ProcessDefinitionEntity> processDefinitions){
This method does not need to return `Void`, you can use `void` without the return null in the end.

2021-10-28 11:23 UTC, erdemedeiros commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/AbstractSetProcessInstanceStateCmd.java
> +  public Void executeInternal(CommandContext commandContext,ExecutionEntity executionEntity){
`Void` --> `void`.

2021-10-28 11:23 UTC, erdemedeiros commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/ChangeDeploymentTenantIdCmd.java
> +  public Void executeInternal(CommandContext commandContext,DeploymentEntity deployment) {
`protected`? `Void` --> `void`.

2021-10-28 11:23 UTC, erdemedeiros commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/DeleteAttachmentCmd.java
> +      return null;
It's better to have `return null` in the main method and use `void` as return type of `excuteInternal`.

2021-10-28 11:23 UTC, erdemedeiros commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/DeleteHistoricProcessInstanceCmd.java
> +  public Object executeInternal(CommandContext commandContext,HistoricProcessInstance instance){
`protected`? `Object` --> `void`

2021-10-28 11:23 UTC, erdemedeiros commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/DeleteAttachmentCmd.java
> +  public Object executeInternal(CommandContext commandContext,AttachmentEntity attachment,String processInstanceId,String processDefinitionId){
`protected`?

2021-10-28 11:23 UTC, erdemedeiros commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/DeleteIdentityLinkForProcessDefinitionCmd.java
> +  public Void executeInternal(CommandContext commandContext,ProcessDefinitionEntity processDefinition) {
`Void` --> `void`.

2021-10-28 11:23 UTC, erdemedeiros commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/DeleteIdentityLinkForProcessInstanceCmd.java
> +  public Void executeInternal(CommandContext commandContext,ExecutionEntity processInstance) {
`protected`? `Void` --> `void`.

2021-10-28 11:23 UTC, erdemedeiros commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/DeleteProcessInstanceCmd.java
> +  public Void executeInternal(CommandContext commandContext,ExecutionEntity processInstanceEntity) {
`protected`? `Void` --> `void`.

2021-10-28 11:23 UTC, erdemedeiros commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/ExecuteJobCmd.java
> +  public Object executeInternal(CommandContext commandContext,Job job) {
`protected`? `Object` --> `void`.

2021-10-28 11:23 UTC, erdemedeiros commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/GetDataObjectCmd.java
> +  public VariableInstance getVariable(ExecutionEntity execution,CommandContext commandContext){
`protected`?

2021-10-28 11:23 UTC, erdemedeiros commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/GetExecutionVariableCmd.java
> +  public Object executeInternal(ExecutionEntity execution,CommandContext commandContext){
`protected`?

2021-10-28 11:23 UTC, erdemedeiros commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/GetExecutionVariableInstanceCmd.java
> +    public VariableInstance getVariable(ExecutionEntity execution,CommandContext commandContext){
`protected`?

2021-10-28 11:23 UTC, erdemedeiros commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/GetExecutionVariableInstancesCmd.java
> +    public  Map<String, VariableInstance> getVariable(ExecutionEntity execution,CommandContext commandContext){
`protected`?

2021-10-28 11:23 UTC, erdemedeiros commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/GetProcessDefinitionInfoCmd.java
> +  public ObjectNode executeInternal(DeploymentManager deploymentManager,CommandContext commandContext,ProcessDefinition processDefinition){
`protected`?

2021-10-28 11:23 UTC, erdemedeiros commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/MessageEventReceivedCmd.java
> +  public Void executeInternal(CommandContext commandContext,ExecutionEntity execution){
`protected`?

2021-10-28 11:23 UTC, erdemedeiros commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/SaveAttachmentCmd.java
> +  public Void executeInternal(CommandContext commandContext, AttachmentEntity updateAttachment,String processInstanceId,String processDefinitionId){
`protected`? `Void` --> `void`.

2021-10-28 11:23 UTC, erdemedeiros commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/SetDeploymentCategoryCmd.java
> +  public Void executeInternal(CommandContext commandContext,DeploymentEntity deployment){
`protected`? `Void` --> `void`.

2021-10-28 11:23 UTC, erdemedeiros commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/SetDeploymentKeyCmd.java
> +  public Void executeInternal(CommandContext commandContext,DeploymentEntity deployment){
`protected`? `Void` --> `void`.

2021-10-28 11:23 UTC, erdemedeiros commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/SetProcessDefinitionCategoryCmd.java
> +  public Void executeInternal(CommandContext commandContext,ProcessDefinitionEntity processDefinition){
`protected`? `Void` --> `void`.

2021-10-28 11:23 UTC, erdemedeiros commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/SetProcessInstanceBusinessKeyCmd.java
> +  public Void executeInternal(CommandContext commandContext,ExecutionEntityManager executionManager,ExecutionEntity processInstance){
`protected`? `Void` --> `void`.

2021-10-28 11:23 UTC, erdemedeiros commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/context/Context.java
> +  //protected static ThreadLocal<ProcessDefinitionHelper> fallbackOldActivitiCompatibilityHandlerThreadLocal = new ThreadLocal<ProcessDefinitionHelper>();
Please, remove commented code.

2021-10-28 11:23 UTC, erdemedeiros commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/deploy/DeploymentManager.java
> +  public ProcessDefinitionCacheEntry resolveProcessDefinitionInternal(CommandContext commandContext,ProcessDefinition processDefinition,String deploymentId, String processDefinitionId){
`protected`?

2021-10-28 11:23 UTC, erdemedeiros commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/deploy/DeploymentManager.java
> +  public void removeDeploymentInternal(String deploymentId, boolean cascade,DeploymentEntity deployment){
`protected`?

2021-10-28 11:23 UTC, erdemedeiros commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/HistoricTaskInstanceEntityManagerImpl.java
> +  public void deleteInternal(String id,HistoricTaskInstanceEntity historicTaskInstance){
`protected`?

2021-10-28 11:23 UTC, erdemedeiros commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/repository/DeploymentProperties.java
> +    String DEPLOY_AS_ACTIVITI5_PROCESS_DEFINITION = "deployAsActiviti5ProcessDefinition";
This constant seems never used here, so it can be removed.

2021-10-29 09:09 UTC, AnkurChauhan-131 commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/GetExecutionVariableCmd.java
> +  public Object executeInternal(ExecutionEntity execution,CommandContext commandContext){
Done as Expected

2021-10-29 09:10 UTC, AnkurChauhan-131 commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/asyncexecutor/ExecuteAsyncRunnable.java
> +  public void runInternal(){
Done as Expected

2021-10-29 09:10 UTC, AnkurChauhan-131 commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/helper/ErrorThrowingEventListener.java
> +  public void onEventInternal(ActivitiEvent event){
Done as Expected

2021-10-29 09:10 UTC, AnkurChauhan-131 commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/AbstractSetProcessDefinitionStateCmd.java
> +  public Void executeInternal(CommandContext commandContext,List<ProcessDefinitionEntity> processDefinitions){
Done as Expected

2021-10-29 09:10 UTC, AnkurChauhan-131 commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/AbstractSetProcessDefinitionStateCmd.java
> +  public void createTimerForDelayedExecution(CommandContext commandContext, List<ProcessDefinitionEntity> processDefinitions) {
Done as Expected

2021-10-29 09:10 UTC, AnkurChauhan-131 commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/AbstractSetProcessDefinitionStateCmd.java
> +  public void createTimerForDelayedExecutionInternal(CommandContext commandContext, ProcessDefinitionEntity processDefinition) {
Done as Expected

2021-10-29 09:10 UTC, AnkurChauhan-131 commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/AbstractSetProcessDefinitionStateCmd.java
> +  public void changeProcessDefinitionState(CommandContext commandContext, List<ProcessDefinitionEntity> processDefinitions) {
Done as Expected

2021-10-29 09:11 UTC, AnkurChauhan-131 commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/AbstractSetProcessInstanceStateCmd.java
> +  public Void executeInternal(CommandContext commandContext,ExecutionEntity executionEntity){
Done as Expected

2021-10-29 09:11 UTC, AnkurChauhan-131 commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/AbstractSetProcessInstanceStateCmd.java
>        }
Done as Expected

2021-10-29 09:11 UTC, AnkurChauhan-131 commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/AbstractSetProcessInstanceStateCmd.java
>        }
Done as Expected

2021-10-29 09:11 UTC, AnkurChauhan-131 commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/AbstractSetProcessInstanceStateCmd.java
>        }
Done as Expected

2021-10-29 09:11 UTC, AnkurChauhan-131 commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/AddCommentCmd.java
> +  public Comment executeInternal(CommandContext commandContext,String processDefinitionId){
Done as Expected

2021-10-29 09:11 UTC, AnkurChauhan-131 commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/AddIdentityLinkForProcessDefinitionCmd.java
> +  public Void executeInternal(CommandContext commandContext,ProcessDefinitionEntity processDefinition) {
Done as Expected

2021-10-29 09:11 UTC, AnkurChauhan-131 commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/AddIdentityLinkForProcessDefinitionCmd.java
> +  public Void executeInternal(CommandContext commandContext,ProcessDefinitionEntity processDefinition) {
Done as Expected

2021-10-29 09:12 UTC, AnkurChauhan-131 commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/AddIdentityLinkForProcessInstanceCmd.java
> +  public Void executeInternal(CommandContext commandContext,ExecutionEntity processInstance) {
Done as Expected

2021-10-29 09:12 UTC, AnkurChauhan-131 commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/AbstractSetProcessDefinitionStateCmd.java
> +  public Void executeInternal(CommandContext commandContext,List<ProcessDefinitionEntity> processDefinitions){
Done as Expected

2021-10-29 09:12 UTC, AnkurChauhan-131 commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/AbstractSetProcessInstanceStateCmd.java
> +  public Void executeInternal(CommandContext commandContext,ExecutionEntity executionEntity){
Done as Expected

2021-10-29 09:12 UTC, AnkurChauhan-131 commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/ChangeDeploymentTenantIdCmd.java
> +  public Void executeInternal(CommandContext commandContext,DeploymentEntity deployment) {
Done as Expected

2021-10-29 09:12 UTC, AnkurChauhan-131 commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/DeleteAttachmentCmd.java
> +      return null;
Done as Expected

2021-10-29 09:12 UTC, AnkurChauhan-131 commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/DeleteHistoricProcessInstanceCmd.java
> +  public Object executeInternal(CommandContext commandContext,HistoricProcessInstance instance){
Done as Expected

2021-10-29 09:12 UTC, AnkurChauhan-131 commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/DeleteAttachmentCmd.java
> +  public Object executeInternal(CommandContext commandContext,AttachmentEntity attachment,String processInstanceId,String processDefinitionId){
Done as Expected

2021-10-29 09:13 UTC, AnkurChauhan-131 commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/DeleteIdentityLinkForProcessDefinitionCmd.java
> +  public Void executeInternal(CommandContext commandContext,ProcessDefinitionEntity processDefinition) {
Done as Expected

2021-10-29 09:13 UTC, AnkurChauhan-131 commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/DeleteIdentityLinkForProcessInstanceCmd.java
> +  public Void executeInternal(CommandContext commandContext,ExecutionEntity processInstance) {
Done as Expected

2021-10-29 09:13 UTC, AnkurChauhan-131 commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/DeleteProcessInstanceCmd.java
> +  public Void executeInternal(CommandContext commandContext,ExecutionEntity processInstanceEntity) {
Done as Expected

2021-10-29 09:13 UTC, AnkurChauhan-131 commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/ExecuteJobCmd.java
> +  public Object executeInternal(CommandContext commandContext,Job job) {
Done as Expected

2021-10-29 09:13 UTC, AnkurChauhan-131 commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/GetDataObjectCmd.java
> +  public VariableInstance getVariable(ExecutionEntity execution,CommandContext commandContext){
Done as Expected

2021-10-29 09:13 UTC, AnkurChauhan-131 commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/GetExecutionVariableInstanceCmd.java
> +    public VariableInstance getVariable(ExecutionEntity execution,CommandContext commandContext){
Done as Expected

2021-10-29 09:13 UTC, AnkurChauhan-131 commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/GetExecutionVariableInstancesCmd.java
> +    public  Map<String, VariableInstance> getVariable(ExecutionEntity execution,CommandContext commandContext){
Done as Expected

2021-10-29 09:14 UTC, AnkurChauhan-131 commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/GetProcessDefinitionInfoCmd.java
> +  public ObjectNode executeInternal(DeploymentManager deploymentManager,CommandContext commandContext,ProcessDefinition processDefinition){
Done as Expected

2021-10-29 09:14 UTC, AnkurChauhan-131 commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/MessageEventReceivedCmd.java
> +  public Void executeInternal(CommandContext commandContext,ExecutionEntity execution){
Done as Expected

2021-10-29 09:14 UTC, AnkurChauhan-131 commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/SaveAttachmentCmd.java
> +  public Void executeInternal(CommandContext commandContext, AttachmentEntity updateAttachment,String processInstanceId,String processDefinitionId){
Done as Expected

2021-10-29 09:14 UTC, AnkurChauhan-131 commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/SetDeploymentCategoryCmd.java
> +  public Void executeInternal(CommandContext commandContext,DeploymentEntity deployment){
Done as Expected

2021-10-29 09:15 UTC, AnkurChauhan-131 commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/SetDeploymentKeyCmd.java
> +  public Void executeInternal(CommandContext commandContext,DeploymentEntity deployment){
Done as Expected

2021-10-29 09:15 UTC, AnkurChauhan-131 commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/SetProcessDefinitionCategoryCmd.java
> +  public Void executeInternal(CommandContext commandContext,ProcessDefinitionEntity processDefinition){
Done as Expected

2021-10-29 09:16 UTC, AnkurChauhan-131 commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/SetProcessInstanceBusinessKeyCmd.java
> +  public Void executeInternal(CommandContext commandContext,ExecutionEntityManager executionManager,ExecutionEntity processInstance){
Done as Expected

2021-10-29 09:16 UTC, AnkurChauhan-131 commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/context/Context.java
> +  //protected static ThreadLocal<ProcessDefinitionHelper> fallbackOldActivitiCompatibilityHandlerThreadLocal = new ThreadLocal<ProcessDefinitionHelper>();
Done as Expected

2021-10-29 09:16 UTC, AnkurChauhan-131 commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/deploy/DeploymentManager.java
> +  public ProcessDefinitionCacheEntry resolveProcessDefinitionInternal(CommandContext commandContext,ProcessDefinition processDefinition,String deploymentId, String processDefinitionId){
Done as Expected

2021-10-29 09:16 UTC, AnkurChauhan-131 commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/deploy/DeploymentManager.java
> +  public void removeDeploymentInternal(String deploymentId, boolean cascade,DeploymentEntity deployment){
Done as Expected

2021-10-29 09:16 UTC, AnkurChauhan-131 commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/HistoricTaskInstanceEntityManagerImpl.java
> +  public void deleteInternal(String id,HistoricTaskInstanceEntity historicTaskInstance){
Done as Expected

2021-10-29 09:16 UTC, AnkurChauhan-131 commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/repository/DeploymentProperties.java
> +    String DEPLOY_AS_ACTIVITI5_PROCESS_DEFINITION = "deployAsActiviti5ProcessDefinition";
Done as Expected

2021-11-02 10:43 UTC, erdemedeiros approved these changes
LGTM!

2021-11-02 10:58 UTC, balsarori requested changes

2021-11-02 10:58 UTC, balsarori commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/util/ProcessDefinitionUtil.java
> +            throw new ActivitiException("Found Old Activiti process definition, but no compatibility handler on the classpath");
Update exception message: `No ProcessDefinitionHelper set in the current context`

2021-11-02 10:58 UTC, balsarori commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/RepositoryServiceImpl.java
> +import org.activiti.engine.impl.cmd.*;
Avoid `*` import.

2021-11-02 10:58 UTC, balsarori commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cfg/ProcessEngineConfigurationImpl.java
> +import org.activiti.engine.*;
Avoid `*` import.

2021-11-02 11:32 UTC, balsarori approved these changes
LGTM

2021-11-02 12:25 UTC, merged