Activiti/Activiti#3765 Add Process Runtime coverage for category field
Activiti/Activiti pull request #3785
Opened 2021-12-16 14:24 UTC by miguelruizdev

Ref: Activiti/Activiti#3765

2021-12-17 11:11 UTC, erdemedeiros requested changes

2021-12-17 11:11 UTC, erdemedeiros commented on activiti-core/activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/process/ProcessRuntimeIT.java
> +        assertThat(processDefinitionQuantity).isEqualTo(processDefinitionNonDistinctCategoryQuantity);
This entire block can be simplified to:

```java
  assertThat(processDefinitionList)
            .extracting(ProcessDefinition::getCategory)
            .contains(CATEGORIZE_HUMAN_PROCESS_CATEGORY)
            .allMatch(Objects::nonNull);
```

2021-12-17 13:18 UTC, miguelruizdev commented on activiti-core/activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/process/ProcessRuntimeIT.java
> +        assertThat(processDefinitionQuantity).isEqualTo(processDefinitionNonDistinctCategoryQuantity);
Cool 🤩

2022-01-04 10:02 UTC, erdemedeiros approved these changes

2022-01-04 10:07 UTC, merged