Update ExtendedInMemoryUserDetailsManager.java
Activiti/Activiti pull request #4304
Opened 2023-04-17 14:28 UTC by FlyingDutchmanLQY

Fix createUser() method.

2023-04-17 14:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Activiti/Activiti?pullRequest=4304) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Activiti/Activiti?pullRequest=4304) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Activiti/Activiti?pullRequest=4304) it.</sub>

2023-04-17 14:35 UTC, FlyingDutchmanLQY commented
#4304

2023-04-19 10:41 UTC, balsarori requested changes
Can you add a unit test?

2023-04-21 06:05 UTC, FlyingDutchmanLQY commented
It is added now @balsarori

2026-04-24 10:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/Activiti/Activiti?pullRequest=4304) <br/>All committers have signed the CLA.

2026-07-28 00:19 UTC, closed without merging