Update ProcessInstanceHelper.java to fix runtime bundle executing wrong start event when start process instance by message [issue #4382]
Activiti/Activiti pull request #4383
Opened 2023-07-24 07:08 UTC by abhinay9955

Update ProcessInstanceHelper.java to fix runtime bundle in activiti cloud executing wrong start event when start process instance by message [issue #4382]

2023-07-24 07:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Activiti/Activiti?pullRequest=4383) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Activiti/Activiti?pullRequest=4383) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Activiti/Activiti?pullRequest=4383) it.</sub>

2023-07-24 09:41 UTC, abhinay9955 commented
Hi @miguelruizdev , can you please review and approve workflow runs
Thank you !!

2023-07-24 12:50 UTC, miguelruizdev commented
Hi @abhinay9955, we would need test coverage in order to accept the Pull Request.
Also, it'd be great if you add @igdianov as a reviewer, since I see he's the author of the code you are deleting.

2023-07-24 13:17 UTC, abhinay9955 commented
Sure @miguelruizdev , Thanks!!

2023-08-07 18:20 UTC, igdianov requested changes
@abhinay9955 I am a concerned that this is going to be a breaking change, ie in APS, that changes the behavior of using a model message ref to find and set message ref to message name by matching it to message id in case the message name is not matching message ref. 

We need to consult with @VitoAlbano who added this code as part of this commit: https://github.com/Activiti/Activiti/commit/6ddaae94ece697dc45fdd0c08ee28d62dda56f96

2023-08-08 09:54 UTC, abhinay9955 commented
Hi @igdianov , i have updated the code , i think this change addresses your concern , Thanks :)

2023-08-08 15:52 UTC, igdianov commented
> Hi @igdianov , i have updated the code , i think this change addresses your concern , Thanks :)

Can you add test coverage for it, please? Thanks!

2023-08-11 02:07 UTC, hexiaokang approved these changes

2023-08-21 16:56 UTC, abhinay9955 commented
Hi @igdianov , added unit tests please review . Thanks :)
Sorry for delay.

2023-09-01 10:36 UTC, abhinay9955 commented
@VitoAlbano please review !! Thanks !!

2023-11-16 11:35 UTC, abhinay9955 commented
Hi @VitoAlbano @igdianov @miguelruizdev , i have added test cases long ago , can you please review .
Thanks in Advance!!

2026-04-24 10:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Activiti/Activiti?pullRequest=4383) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Activiti/Activiti?pullRequest=4383) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Activiti/Activiti?pullRequest=4383) it.</sub>

2026-07-28 00:19 UTC, closed without merging