MNT-24219: local variables before calling subprocess remains after en…
Activiti/Activiti pull request #4596
Opened 2024-02-21 11:29 UTC by vrmoreira

…d of subprocess

**What kind of change does this PR introduce?**

> - [X] Bugfix
> - [ ] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

## Description

- Issue Link: https://alfresco.atlassian.net/browse/MNT-24219

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [X] No

2024-02-21 11:30 UTC, vrmoreira commented
Tried to make the fix as clear as possible.
Anyway, think this diagram might shed some light. If this solution is approved, then I'll update the JIRA ticket
![diagram](https://github.com/Activiti/Activiti/assets/6524103/862b71c0-bcbb-4539-9bd9-25e8174c4a6c)

2024-02-29 10:20 UTC, erdemedeiros requested changes

2024-02-29 10:20 UTC, erdemedeiros commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/agenda/EndExecutionOperation.java
> +        }
This logic only works for some specific cases, but it cannot work in general: `parentExecution.getParent().getExecutions()` may return several executions depending on the process design and peeking the first one could return the wrong one. Also, there is no guarantee that the execution we are looking for is still in the database at this point, as it's marked to be deleted in [ContinueProcessOperation.createChildExecutionForSubProcess](https://github.com/Activiti/Activiti/blob/develop/activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/agenda/ContinueProcessOperation.java#L142) and depending on the process design it may or may not be there. For instance, if the subprocess has a user task or any flow node marked as async, the execution will be already deleted from the database when we reach this point.

2024-03-01 10:51 UTC, vrmoreira commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/agenda/EndExecutionOperation.java
> +        }
I've improved the fetch of the execution but it fails when a UserTask is inside of the subprocess: the execution was already deleted. 
Pushed modifications in order to continue the discussion

2026-04-24 10:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/Activiti/Activiti?pullRequest=4596) <br/>All committers have signed the CLA.

2026-07-28 00:19 UTC, closed without merging