AAE-22465 Added logic to validate the cardinality
Activiti/Activiti pull request #4654
Opened 2024-05-10 11:27 UTC by AkhileshPamidimarthi

**What kind of change does this PR introduce?**

> - [x] Bugfix
> - [ ] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

## Description

- Issue Link:

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [x] No

2024-05-10 14:10 UTC, eromano requested changes
I would prefer review our approach here with @gicappa @igdianov @erdemedeiros

2024-05-27 08:07 UTC, jesty requested changes

2024-05-27 08:07 UTC, jesty commented on activiti-core/activiti-process-validation/src/main/java/org/activiti/validation/validator/Problems.java
> +    String MULTI_INSTANCE_HIGHER_CARDINALITY = "activiti-multi-instance-cardinality-greater-than-200";
can u fix formatting? Thanks!

2024-05-27 08:07 UTC, jesty commented on activiti-core/activiti-process-validation/src/main/java/org/activiti/validation/validator/impl/FlowElementValidator.java
> +                        addError(errors, Problems.MULTI_INSTANCE_HIGHER_CARDINALITY, process, activity,
please replace addError with addWarning

2024-05-28 15:30 UTC, jesty requested changes

2024-05-28 15:30 UTC, jesty commented on activiti-core/activiti-process-validation/src/main/java/org/activiti/validation/validator/impl/FlowElementValidator.java
> +                    if(loopCardinality >200){
can we extract the value in an external property? thanks

2024-05-29 10:13 UTC, jesty requested changes

2024-05-29 10:13 UTC, jesty commented on activiti-core/activiti-process-validation/src/main/java/org/activiti/validation/validator/impl/FlowElementValidator.java
> +    @Value("${loop.cardinality.threshold}")
add a blank new line above, prefix it with acitivi and specify the default value here.
```suggestion

    @Value("${activiti.loop.cardinality.threshold:200}")
```

2024-05-29 10:13 UTC, jesty commented on activiti-core/activiti-process-validation/src/main/resources/application.properties
> +loop.cardinality.threshold=200
specifying the default value, then, we can remove it

2024-06-03 08:48 UTC, jesty commented
> I would prefer review our approach here with @gicappa @igdianov @erdemedeiros, let's have a call next week

Hi @eromano we changed to warning. @gicappa @igdianov @erdemedeiros what do you think? 

I asked to add a warning because in my tests I noticed that when we have many parallelel task to create we can face 500 errors because the operation it's going to be really long.

2024-06-04 16:26 UTC, igdianov requested changes
@jesty Could add unit tests to make sure there is coverage against future regressions?

2024-06-04 16:26 UTC, igdianov commented on activiti-core/activiti-process-validation/pom.xml
> +      <dependency>
Is it really needed to include the dependency from Spring in the core engine?

2024-06-04 16:26 UTC, igdianov commented on activiti-core/activiti-process-validation/src/main/java/org/activiti/validation/validator/impl/FlowElementValidator.java
> +    @Value("${loop.cardinality.threshold:200}")
It is not a good practice to use Spring value injection. The core validation configuration approach should not rely on Spring field injection to configure parameter limits.

2024-06-04 16:26 UTC, igdianov commented on activiti-core/activiti-process-validation/src/main/java/org/activiti/validation/validator/impl/FlowElementValidator.java
> -	  }
Could you restore original indents to keep the formatting consistent for easier code review?

2024-06-13 12:59 UTC, closed without merging

2024-06-13 13:00 UTC, jesty commented
We are going to put the async flag in the UI