AAE-24223 - Fixed PersistenceException by adding order annotation to …
Activiti/Activiti pull request #4738
Opened 2024-08-07 08:22 UTC by AkhileshPamidimarthi

…make the ShutdownListener run first when spring context is closed.

**What kind of change does this PR introduce?**

> - [x] Bugfix
> - [ ] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

## Description

- Issue Link: https://hyland.atlassian.net/browse/AAE-24223

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [x] No

2024-08-07 08:54 UTC, jesty requested changes

2024-08-07 08:54 UTC, jesty commented on activiti-core/activiti-spring-boot-starter/src/main/java/org/activiti/spring/boot/ShutdownListener.java
> +@Component
we are defining the bean in ProcessEngineAutoConfiguration so we should configure there.
Can you try to build an image and check the log on an env? thanks

2024-09-18 06:20 UTC, tom-dal approved these changes
LGTM

2024-09-19 09:02 UTC, jesty approved these changes
LGTM

2024-09-19 14:18 UTC, merged