AAE-23375 Fixed the issue to import a project with multiInstance with…
Activiti/Activiti pull request #4771
Opened 2024-08-27 14:23 UTC by AkhileshPamidimarthi

… null as cardinality

**What kind of change does this PR introduce?**

> - [x] Bugfix
> - [ ] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

## Description

- Issue Link: https://hyland.atlassian.net/browse/AAE-23375

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [x] No

2024-08-27 14:37 UTC, jesty requested changes

2024-08-27 14:37 UTC, jesty commented on activiti-core/activiti-bpmn-converter/src/main/java/org/activiti/bpmn/converter/export/MultiInstanceExport.java
> +      else{
this else statement containse the first line of the if above, so proabably we can just move out of the if. Can you also add a test? Thanks!

2024-08-28 09:37 UTC, jesty commented on activiti-core/activiti-bpmn-converter/src/test/java/org/activiti/bpmn/converter/export/MultiInstanceExportTest.java
> +        verify(xtw).writeStartElement("multiInstanceLoopCharacteristics");
can we verify the generated XML?

2024-08-28 13:12 UTC, jesty commented on activiti-core/activiti-bpmn-converter/src/test/java/org/activiti/bpmn/converter/export/MultiInstanceExportTest.java
> +public class MultiInstanceExportTest {
should we test also when the tag it's empty?  I'm expecting a test with an assert like:
`assertTrue(generatedXml.contains("<multiInstanceLoopCharacteristics />"));`
Or am I wrong? Thanks

2024-08-29 09:17 UTC, balsarori commented on activiti-core/activiti-bpmn-model/src/main/java/org/activiti/bpmn/model/MultiInstanceLoopCharacteristics.java
> +  private Boolean sequential;
Why change to it a `Boolean`? sequential should be `false` by default. Now there needs to lots of null checks.

2024-09-03 22:21 UTC, jesty approved these changes
LGTM

2024-09-10 08:23 UTC, merged