AAE-23403 Disable timers and events from process definitions
Activiti/Activiti pull request #4802
Opened 2024-10-13 07:14 UTC by revatilimaye

**What kind of change does this PR introduce?**

> - [ ] Bugfix
> - [ ] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [x] Other... Please describe:

## Description

- Issue Link: https://hyland.atlassian.net/browse/AAE-23403

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [x] No

2024-10-17 14:16 UTC, CaptainGlac1er commented
I'm interested in learning more about this ticket however am not able to access the jira link?

2025-02-18 18:15 UTC, erdemedeiros requested changes
Good job! I've add some suggestion of renaming and other small details.

2025-02-18 18:15 UTC, erdemedeiros commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/ProcessEngineConfiguration.java
> +  protected boolean disableAllPreviousStartEvents;
I think this can be renamed to `disableExistingStartEventSubscriptions` where `subscriptions` is the generic term to reference signal, messages and timers.

2025-02-18 18:15 UTC, erdemedeiros commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/deployer/BpmnDeployer.java
> +    private boolean disableAllStartEvents;
`disableExistingStartEventSubscriptions`

2025-02-18 18:15 UTC, erdemedeiros commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/deployer/BpmnDeployer.java
> +                bpmnDeploymentHelper.disableTimerMessageAndSignalStartEvents();
`disableExistingStartEventSubscriptions`

2025-02-18 18:15 UTC, erdemedeiros commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/deployer/BpmnDeploymentHelper.java
> +    protected enum ExpressionType {
If possible, it's better to keep the existing indentation for this (at least for the latest line)

2025-02-18 18:15 UTC, erdemedeiros commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/deployer/EventSubscriptionManager.java
> +    protected void removeObsoleteSignalStartEventSubscriptions() {
`removeExistingSignalEventSubscriptions`

2025-02-18 18:15 UTC, erdemedeiros commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/deployer/EventSubscriptionManager.java
> +    protected void removeObsoleteMessageStartEventSubscriptions() {
`removeExistingMessageStartEventSubscription`

2025-02-18 18:15 UTC, erdemedeiros commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/deployer/TimerManager.java
> +  protected void removeObsoleteTimerStartEvents() {
`removeExistingTimerStartEventJobs`

2025-02-18 18:15 UTC, erdemedeiros commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/deployer/TimerManager.java
> +    if (timerStartJobs != null && timerStartJobs.size() > 0) {
Checking if the collection is empty is redundant: the `for` loop will already be skipped in the case where the collection is empty. Only the null check is needed.

2025-02-18 18:15 UTC, erdemedeiros commented on activiti-core/activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/ApplicationUpgradeIT.java
> +        assert !activitiProperties.isDisableAllPreviousStartEvents();
Please, use AssertJ assertions: `assertThat(activitiProperties.isDisableAllPreviousStartEvents()).isFalse()`

2025-02-18 18:15 UTC, erdemedeiros commented on activiti-core/activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/ApplicationUpgradeIT.java
> +        List<Job> list = managementService.createTimerJobQuery().processDefinitionId(processDefinition.getId()).list();
The variable can be renamed to `jobs`.

2025-02-18 18:15 UTC, erdemedeiros commented on activiti-core/activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/ApplicationUpgradeIT.java
> +            .isEqualTo(Arrays.asList(processDefinition.getId()));
This can be simplified to:
```java
    assertThat(list)
            .extracting(Job::getProcessDefinitionId)
            .containsExactly(processDefinition.getId());
```
The assertion `containsExactly` will already fail if the size is is different then the one expected.

2025-02-18 18:15 UTC, erdemedeiros commented on activiti-core/activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/ApplicationUpgradeIT.java
> +            .isEqualTo(Arrays.asList(processDefinition.getId()));
Same here.

2025-02-18 18:15 UTC, erdemedeiros commented on activiti-core/activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/ApplicationUpgradeIT.java
> +        List<EventSubscriptionEntity> messageSubscriptions = eventSubscriptionQuery.eventType("message").activityId("Event_1").list();
Could you update the process definition used by this test to make the `activityId` more specific and avoid potential conflicts?  `Event_1 ` is too generic.

2025-02-18 18:15 UTC, erdemedeiros commented on activiti-core/activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/ApplicationUpgradeIT.java
> +    public void should_deletePreviousSignalStartEvents_when_projectIsUpgraded_and_disableStartEventsIsFalse() {
should_not?

2025-02-18 18:15 UTC, erdemedeiros commented on activiti-core/activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/ApplicationUpgradeIT.java
> +        List<EventSubscriptionEntity> signalSubscriptions = eventSubscriptionQuery.eventType("signal").activityId("Event_1").list();
Same here: let's update the related process definition to make `activityId` more specific.

2025-02-18 18:15 UTC, erdemedeiros commented on activiti-core/activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/ApplicationUpgradeWithStartEventsIT.java
> +    ManagementService managementService;
`private`

2025-02-18 18:15 UTC, erdemedeiros commented on activiti-core/activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/ApplicationUpgradeWithStartEventsIT.java
> +        assert activitiProperties.isDisableAllPreviousStartEvents();
Please, use `AssertJ` assertions.

2025-02-18 18:15 UTC, erdemedeiros commented on activiti-core/activiti-spring-boot-starter/src/test/resources/processes/ProcessWithoutMessageStartEvent.bpmn20.xml
> +  <bpmn2:message id="Message_08rsbt0" name="Message_08rsbt0" />
I think you can remove this message declaration from here.

2025-02-18 18:15 UTC, erdemedeiros commented on activiti-core/activiti-spring-boot-starter/src/test/resources/processes/ProcessWithoutSignalStartEvent.bpmn20.xml
> +  <bpmn2:signal id="Signal_0vq9okx" name="Signal_0vq9okx" />
I think this signal can be removed as it's no longer referenced.

2025-02-18 18:15 UTC, erdemedeiros commented on activiti-core/activiti-engine/src/main/java/org/activiti/engine/ProcessEngineConfiguration.java
> +  public boolean isDisableAllPreviousStartEvents(){
I know that `is` is the usual prefix that we give for boolean properties, but I think that in this specific case using `should` prefix will improve the code readability: `shouldDisableExistingStartEventSubscriptions`. WDYT?

2025-02-18 18:15 UTC, erdemedeiros commented on activiti-core/activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/ApplicationUpgradeIT.java
> +    ManagementService managementService;
`private`

2025-02-19 08:36 UTC, erdemedeiros commented
Hi @CaptainGlac1er, unfortunately jira tickets are not publicly available and maintaining mirrored Github issues was taking too much effort from the team. All you need to know about the changes in this PR is that it allows disabling all the existing event subscriptions (timers, signals and messages) for start events related to previous deployments by setting the property `spring.activiti.disable-existing-start-event-subscriptions` to `true`. This is useful in the case where you're using a single deployment with the latest version of your process definitions and keeping the previous deployments only to handle on fly process-instances (in which case you don't want process definitions from there to start new process-instances via start events)

2025-02-19 08:41 UTC, erdemedeiros approved these changes

2025-02-19 08:43 UTC, merged